const SHOW_NEWS = "SHOW_NEWS";
const SHOW_HOME = "SHOW_HOME";
const HIDE_HOME = "HIDE_HOME";
const SHOW_SETTING = "SHOW_SETTING";
const HIDE_SETTING = "HIDE_SETTING";
export {  SHOW_NEWS,SHOW_HOME,HIDE_HOME,SHOW_SETTING,HIDE_SETTING };
